use crate::cfg::guards::{FactConfidence, InstructionAnalysisContext, SymbolId};
use crate::Workspace;
use serde::{Deserialize, Serialize};

pub mod dominance;
pub mod epic_sec_001;
pub mod epic_sec_002;
pub mod epic_sec_003;
pub mod epic_sec_004;
pub mod epic_sec_005;
pub mod resolver;

pub use dominance::DominanceChecker;
pub use epic_sec_001::OwnerValidationRule;
pub use epic_sec_002::SignerValidationRule;
pub use epic_sec_003::MissingPostCpiReloadRule;
pub use epic_sec_004::PdaSeedCollisionRule;
pub use epic_sec_005::ArbitraryCpiTargetRule;
pub use resolver::SymbolResolver;

/// Represents the severity levels for findings generated by the rule engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RuleSeverity {
    Warning,
    Medium,
    High,
    Critical,
}

/// Structured location of a finding in the source code.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FindingLocation {
    pub file: String,
    pub line: usize,
    pub column: usize,
    pub node_id: usize,
    pub statement_index: Option<usize>,
}

/// The diagnostic output model representing a security finding.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuleDiagnostic {
    pub rule_id: String,
    pub severity: RuleSeverity,
    pub message: String,
    pub location: FindingLocation,
    pub confidence: FactConfidence,
    pub target_symbol: SymbolId,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProgramMetadata {
    pub name: String,
    pub address: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlMetadata {
    pub version: String,
    pub name: String,
    pub raw_json: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuleMetadata {
    pub id: String,
    pub name: String,
    pub severity: RuleSeverity,
    pub description: String,
}

/// The canonical analysis context containing all graphs and metadata passed to security rules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisContext {
    pub program_metadata: ProgramMetadata,
    pub idl_metadata: Option<IdlMetadata>,
    pub ast_graph: Workspace,
    pub instruction_context: InstructionAnalysisContext,
    pub rule_registry: Vec<RuleMetadata>,
}

impl AnalysisContext {
    pub fn resolver(&self) -> SymbolResolver {
        SymbolResolver::new(&self.instruction_context)
    }

    pub fn dominance(&self) -> DominanceChecker {
        DominanceChecker::new(&self.instruction_context.cfg)
    }
}

/// Interface for all EPIC security rules.
pub trait Rule: Send + Sync {
    /// Return the static canonical rule identifier (e.g., "EPIC-SEC-001").
    fn id(&self) -> &'static str;
    /// Return the human-readable description of the rule.
    fn name(&self) -> &'static str;
    /// Run the rule check against the unified AnalysisContext.
    fn check(
        &self,
        context: &AnalysisContext,
    ) -> Vec<RuleDiagnostic>;
}

/// Executes all registered rules against analysis contexts.
pub struct RuleEngine {
    rules: Vec<Box<dyn Rule>>,
}

impl RuleEngine {
    pub fn new() -> Self {
        Self { rules: Vec::new() }
    }

    pub fn register_rule(&mut self, rule: Box<dyn Rule>) {
        self.rules.push(rule);
    }

    pub fn run_all(&self, context: &AnalysisContext) -> Vec<RuleDiagnostic> {
        let mut diagnostics = Vec::new();
        for rule in &self.rules {
            diagnostics.extend(rule.check(context));
        }
        diagnostics
    }
}
